# -*- coding: utf-8 -*-
"""mastermind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JL7pfqKufXLYA8Dn1YzE7LSMBurswzrt
"""

from random import randint
import random
class mastermind:

    def __init__():
        pass
    
    def description():
        print("Hello this is mastermind, a game where you make a guess of any 4 digit number ranging from 0000 to 9999.\n")
        print("If you guessed the correct number under 10 tries, you won the game.\n")
        print("Within the first ten tries, I will provide you with clues to help you get closer to the answer!\n")
        print("For each wrong guess, I will tell you the number of digits that are in the same position as the answer, denoted by P\n")
        print("And the number of correct digits that are in the wrong position as the answer, denoted by N.\n")
        print("For example, If your second guess was 7777 and the answer is 9797, I will display \n" )
        print("[Guess: 7777. Result: 0N, 2P Tries Left: 8]\n")
        print("For example, If your second guess was 7979 and the answer is 9797, I will display \n" )
        print("[Guess: 7979. Result: 4N, 0P Tries Left: 8]\n")

    def game():
        first = str(randint(0, 9))
        second = str(randint(0, 9))
        third = str(randint(0, 9))
        fourth = str(randint(0, 9))
        # string of random characters form random number
        rn = first+second+third+fourth 
        tries = 10 # initialize

        for i in range(tries+1): # iterating through 10 times
            # input guess
            g = input("Enter your guess (eg. 0123 or 3579): ") 
            # type break to quit
            if g == 'break':
                break
            # check length of input and if the input is numerical
            elif len(g) != 4 or g.isnumeric() == False:
                print("Invalid Input")
            # proceed
            else:
            # convert input to string
                str_guess = str(g)
            # initialize p
                p = 0
                nodouble=[] # create list of p
                for i in [0,1,2,3]:
                    if str_guess[i] == rn[i]: # match each character of guess and random number
                        nodouble.append(str_guess[i]) # add to list of nodouble
                        p+=1 # add one to p
                n = 0 # initialize
                for y in [0,1,2,3]:
                # for each index, check that the characters don't match
                # if characters in the random number are present in the guess
                # last, check if the random number exists in the nodouble list to prevent duplicates
                    if str_guess[y] != rn[y] and rn[y] in str_guess and rn[y] not in nodouble:
                        n+=1 # after meeting the conditions, add one to n
                if p < 4 and tries == 1: # if p is not 4 and number of tries is zero, game over
                    print("Game Over! The number was "+rn+".")
                elif p < 4: # if p is not 4 and tries is more than zero, 
                    tries -= 1 # subtract one from tries
                    print("Your guess was "+str_guess+". Result: "+str(n)+ "N, "+str(p)+"P Tries Left: "+str(tries))
                    # update user on performance
                else:
                    # or else, the game is won, break the loop
                    print("You’ve won! The number was "+rn+"!")
                    break

print(mastermind.description())

# game
print(mastermind.game())
